name: "C# Security scanning"

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/workflows/build.yml
      - .github/workflows/skipped-build.yml
      - .github/CODEOWNERS
      - .github/dependabot.yml
      - '.vscode/**'
      - .editorconfig
      - LICENSE
      - README.md
  schedule:
    - cron: '39 13 * * 5'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}

    - name: Autobuild
      uses: github/codeql-action/autobuild@v1

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
